services:
  app:
    build:
      context: .
    image: next-pi
    ports:
      - 8585:8585
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - ./node_modules/
        - action: rebuild
          path: ./package.json
